"""V2-T 分析層:績效指標(T1)/ walk-forward(T2)/ lock(T4)。"""
from .metrics import (
    PERIODS_PER_YEAR_DAILY,
    PerformanceMetrics,
    cagr,
    calmar,
    compute_metrics,
    daily_equity,
    equity_returns,
    max_drawdown,
    metrics_from_curve,
    rolling_sharpe,
    sharpe,
    sortino,
)
from .walk_forward import (
    SplitResult,
    WalkForwardResult,
    WindowResult,
    add_months,
    single_split,
    slice_series,
    walk_forward,
    windows,
)
from .regime import (
    CHOP,
    DOWN,
    TREND_THRESHOLD_DEFAULT,
    UP,
    RegimeBucket,
    bucket_windows,
    classify,
    closes_in_range,
    efficiency_ratio,
    net_return,
)

__all__ = [
    "PERIODS_PER_YEAR_DAILY",
    "PerformanceMetrics",
    "SplitResult",
    "WalkForwardResult",
    "WindowResult",
    "add_months",
    "cagr",
    "calmar",
    "compute_metrics",
    "daily_equity",
    "equity_returns",
    "max_drawdown",
    "metrics_from_curve",
    "rolling_sharpe",
    "sharpe",
    "single_split",
    "slice_series",
    "sortino",
    "walk_forward",
    "windows",
    # regime
    "CHOP",
    "DOWN",
    "TREND_THRESHOLD_DEFAULT",
    "UP",
    "RegimeBucket",
    "bucket_windows",
    "classify",
    "closes_in_range",
    "efficiency_ratio",
    "net_return",
]
